"""HTTP integration coverage for single biometric enrollment/replace/delete.

Uses the real router -> service -> repository -> Postgres path via
``client_db``/``db_session`` (see app/tests/conftest.py). Covers
role/ownership authorization, the create/replace/delete/finalize
lifecycle, duplicate-content rejection, inactive-student rejection, and
audit-log creation. Storage- and image-validation-level edge cases are
covered in their own unit test files
(test_phase5_stage2_storage.py / test_phase5_stage2_image_validation.py)
and are not repeated here — only what the HTTP layer itself adds.
"""

from __future__ import annotations

from datetime import datetime

import pytest
from httpx import AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.attendance.models import AuditLog, AuditOutcome
from app.modules.biometric_enrollment.models import (
    BiometricEnrollment,
    BiometricSample,
    EnrollmentStatus,
    SampleStatus,
)
from app.tests.phase3_http_helpers import auth_headers
from app.tests.phase5_stage2_http_helpers import (
    make_jpeg_bytes,
    make_png_bytes,
    seed_enrollment_scope,
    upload_sample,
)


async def test_create_sample_unauthenticated_returns_401(client_db: AsyncClient) -> None:
    response = await client_db.post(
        "/api/v1/biometric-enrollments/00000000-0000-0000-0000-000000000000/samples",
        files={"file": ("a.jpg", make_jpeg_bytes(), "image/jpeg")},
    )
    assert response.status_code == 401


async def test_create_sample_forbidden_for_teacher(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="teacher-403")
    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["teacher"],
        content=make_jpeg_bytes(),
    )
    assert response.status_code == 403


async def test_create_sample_forbidden_for_student(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="student-403")
    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["student_1"],
        content=make_jpeg_bytes(),
    )
    assert response.status_code == 403


async def test_admin_create_sample_succeeds_and_response_is_safe_metadata_only(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="create-ok")
    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )
    assert response.status_code == 201, response.text
    body = response.json()

    assert body["status"] == "active"
    assert body["processing_state"] == "pending_processing"
    assert body["content_type"] == "image/jpeg"
    assert body["width_px"] == 200
    assert len(body["sha256_hash"]) == 64
    # Never a storage key, absolute path, or temp path anywhere in the body.
    serialized = str(body)
    assert "storage_key" not in body
    assert "/tmp" not in serialized
    assert "var/biometric_data" not in serialized


async def test_create_sample_refreshes_updated_at_before_response_serialization(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    """Real-PostgreSQL regression for the former MissingGreenlet path."""
    scope = await seed_enrollment_scope(client_db, db_session, suffix="create-refresh")

    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )

    assert response.status_code == 201, response.text
    body = response.json()
    assert body["status"] == "active"
    # ``updated_at`` is generated by PostgreSQL's activation UPDATE. Before
    # the fix, extracting this field after commit attempted implicit async
    # ORM I/O and raised MissingGreenlet instead of returning an HTTP response.
    assert datetime.fromisoformat(body["updated_at"]).tzinfo is not None


async def test_create_sample_when_already_active_returns_409(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="already-active")
    first = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )
    assert first.status_code == 201

    second = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=make_png_bytes(),
        filename="second.png",
        content_type="image/png",
    )
    assert second.status_code == 409
    assert second.json()["error"]["code"] == "ENROLLMENT_ALREADY_ACTIVE"


async def test_create_sample_for_inactive_student_returns_409(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="inactive-student")
    patch_response = await client_db.patch(
        f"/api/v1/student-profiles/{scope['student_profile_1']['id']}",
        json={"is_active": False},
        headers=auth_headers(scope["admin"]),
    )
    assert patch_response.status_code == 200

    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )
    assert response.status_code == 409
    assert response.json()["error"]["code"] == "ENROLLMENT_INACTIVE_STUDENT"


async def test_create_sample_with_corrupt_image_returns_422(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="corrupt")
    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=b"this is not a real image file" * 10,
    )
    assert response.status_code == 422
    assert response.json()["error"]["code"] == "ENROLLMENT_IMAGE_DECODE_FAILED"


async def test_create_sample_over_configured_byte_cap_returns_413(
    client_db: AsyncClient, db_session: AsyncSession, monkeypatch: pytest.MonkeyPatch
) -> None:
    import app.modules.biometric_enrollment.service as service_module
    from app.core.config import get_settings

    small_cap_settings = get_settings().model_copy(update={"MAX_ENROLLMENT_IMAGE_BYTES": 100})
    monkeypatch.setattr(service_module, "get_settings", lambda: small_cap_settings)

    scope = await seed_enrollment_scope(client_db, db_session, suffix="too-large")
    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=make_jpeg_bytes(size=(400, 400)),
    )
    assert response.status_code == 413
    assert response.json()["error"]["code"] == "ENROLLMENT_IMAGE_TOO_LARGE"


async def test_replace_sample_with_no_existing_active_returns_409(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="replace-no-active")
    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=make_jpeg_bytes(),
        method="put",
    )
    assert response.status_code == 409
    assert response.json()["error"]["code"] == "ENROLLMENT_NO_ACTIVE_SAMPLE"


async def test_replace_sample_succeeds_and_retires_old_sample(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="replace-ok")
    student_profile_id = scope["student_profile_1"]["id"]

    created = await upload_sample(
        client_db,
        student_profile_id=student_profile_id,
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )
    assert created.status_code == 201
    old_sample_id = created.json()["id"]

    replaced = await upload_sample(
        client_db,
        student_profile_id=student_profile_id,
        user=scope["admin"],
        content=make_png_bytes(),
        filename="new.png",
        content_type="image/png",
        method="put",
    )
    assert replaced.status_code == 200, replaced.text
    body = replaced.json()
    assert body["previous_sample_id"] == old_sample_id
    assert body["new_sample"]["status"] == "active"
    assert body["new_sample"]["content_type"] == "image/png"

    old_sample = await db_session.get(BiometricSample, old_sample_id)
    assert old_sample is not None
    assert old_sample.status is SampleStatus.DELETED


async def test_replace_with_identical_content_returns_duplicate_conflict(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="replace-dup")
    student_profile_id = scope["student_profile_1"]["id"]
    content = make_jpeg_bytes()

    created = await upload_sample(
        client_db, student_profile_id=student_profile_id, user=scope["admin"], content=content
    )
    assert created.status_code == 201

    replaced = await upload_sample(
        client_db,
        student_profile_id=student_profile_id,
        user=scope["admin"],
        content=content,
        method="put",
    )
    assert replaced.status_code == 409
    assert replaced.json()["error"]["code"] == "ENROLLMENT_DUPLICATE_CONTENT"


async def test_identical_content_across_different_students_is_allowed(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="cross-student-dup")
    content = make_jpeg_bytes()

    first = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=content,
    )
    second = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_2"]["id"],
        user=scope["admin"],
        content=content,
    )
    assert first.status_code == 201
    assert second.status_code == 201


async def test_admin_can_read_any_student_enrollment(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="read-admin")
    student_profile_id = scope["student_profile_1"]["id"]
    await upload_sample(
        client_db,
        student_profile_id=student_profile_id,
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )
    response = await client_db.get(
        f"/api/v1/biometric-enrollments/{student_profile_id}", headers=auth_headers(scope["admin"])
    )
    assert response.status_code == 200
    body = response.json()
    assert body["enrollment"]["status"] == "active"
    assert len(body["samples"]) == 1


async def test_student_can_read_own_enrollment(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="read-self")
    student_profile_id = scope["student_profile_1"]["id"]
    await upload_sample(
        client_db,
        student_profile_id=student_profile_id,
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )
    response = await client_db.get(
        f"/api/v1/biometric-enrollments/{student_profile_id}",
        headers=auth_headers(scope["student_1"]),
    )
    assert response.status_code == 200


async def test_student_reading_another_students_enrollment_is_concealed_404_and_audited(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="read-blocked")
    student_profile_id = scope["student_profile_1"]["id"]
    await upload_sample(
        client_db,
        student_profile_id=student_profile_id,
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )

    response = await client_db.get(
        f"/api/v1/biometric-enrollments/{student_profile_id}",
        headers=auth_headers(scope["student_2"]),
    )
    assert response.status_code == 404

    blocked_logs = (
        (
            await db_session.execute(
                select(AuditLog).where(
                    AuditLog.actor_user_id == scope["student_2"].id,
                    AuditLog.outcome == AuditOutcome.BLOCKED,
                    AuditLog.action == "biometric_enrollment.read",
                )
            )
        )
        .scalars()
        .all()
    )
    assert len(blocked_logs) == 1


async def test_teacher_cannot_read_enrollment(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="teacher-read-403")
    response = await client_db.get(
        f"/api/v1/biometric-enrollments/{scope['student_profile_1']['id']}",
        headers=auth_headers(scope["teacher"]),
    )
    assert response.status_code == 403


async def test_successful_create_writes_success_audit_log(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="audit-success")
    response = await upload_sample(
        client_db,
        student_profile_id=scope["student_profile_1"]["id"],
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )
    assert response.status_code == 201

    success_logs = (
        (
            await db_session.execute(
                select(AuditLog).where(
                    AuditLog.actor_user_id == scope["admin"].id,
                    AuditLog.outcome == AuditOutcome.SUCCESS,
                    AuditLog.action == "biometric_enrollment.sample_create",
                )
            )
        )
        .scalars()
        .all()
    )
    assert len(success_logs) == 1
    expected_student_profile_id = scope["student_profile_1"]["id"]
    actual_student_profile_id = success_logs[0].event_metadata.get("student_profile_id")
    assert actual_student_profile_id == expected_student_profile_id


async def test_request_deletion_without_prior_enrollment_returns_404(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="delete-404")
    response = await client_db.delete(
        f"/api/v1/biometric-enrollments/{scope['student_profile_1']['id']}",
        headers=auth_headers(scope["admin"]),
    )
    assert response.status_code == 404


async def test_full_deletion_lifecycle_and_idempotent_finalize(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="delete-full")
    student_profile_id = scope["student_profile_1"]["id"]
    created = await upload_sample(
        client_db,
        student_profile_id=student_profile_id,
        user=scope["admin"],
        content=make_jpeg_bytes(),
    )
    assert created.status_code == 201
    sample_id = created.json()["id"]

    delete_response = await client_db.delete(
        f"/api/v1/biometric-enrollments/{student_profile_id}", headers=auth_headers(scope["admin"])
    )
    assert delete_response.status_code == 200
    assert delete_response.json()["status"] == "deleted"

    enrollment_id = delete_response.json()["id"]
    enrollment = await db_session.get(BiometricEnrollment, enrollment_id)
    assert enrollment is not None
    assert enrollment.status is EnrollmentStatus.DELETED

    sample = await db_session.get(BiometricSample, sample_id)
    assert sample is not None
    assert sample.status is SampleStatus.DELETED
    assert sample.deleted_at is not None

    # Idempotent retry: calling finalize again is a safe no-op.
    finalize_response = await client_db.post(
        f"/api/v1/biometric-enrollments/{student_profile_id}/deletion/finalize",
        headers=auth_headers(scope["admin"]),
    )
    assert finalize_response.status_code == 200
    assert finalize_response.json()["status"] == "deleted"


async def test_reenrollment_after_full_deletion_with_identical_content_is_allowed(
    client_db: AsyncClient, db_session: AsyncSession
) -> None:
    scope = await seed_enrollment_scope(client_db, db_session, suffix="reenroll")
    student_profile_id = scope["student_profile_1"]["id"]
    content = make_jpeg_bytes()

    first = await upload_sample(
        client_db, student_profile_id=student_profile_id, user=scope["admin"], content=content
    )
    assert first.status_code == 201

    delete_response = await client_db.delete(
        f"/api/v1/biometric-enrollments/{student_profile_id}", headers=auth_headers(scope["admin"])
    )
    assert delete_response.status_code == 200

    second = await upload_sample(
        client_db, student_profile_id=student_profile_id, user=scope["admin"], content=content
    )
    assert second.status_code == 201
